### ISSUE TITLE
Usage Example

### ISSUE THREAD

**Issue by srinibalakrishnan** [mellowcandle/bellwin_usb_linux_driver#1]
Hi,
i have a need to use the bellwin USB Power splitter on linux system. Do you have any sample code on how to use this linux driver using python?

**Comment by mellowcandle** [comment]
Hi. sorry it's not working, I started tinkering with it but I no longer have access to the HW to continue

**Comment by srinibalakrishnan** [comment]
Hi,
Thanks for the update.

**Comment by mellowcandle** [comment]
Hi @srinibalakrishnan 
I got access to HW and finished the driver. feel free to use it.
